name: Install winget
description: Installs the latest version of winget
author: Dominion/Cyberboss
branding:
  icon: arrow-down-circle
  color: blue
inputs:
  GITHUB_TOKEN:
    description: 'No scopes GitHub token for querying the API and downloading from winget-cli releases'
    required: false
    default: 'NONE'
outputs:
  winget-version:
    description: "The version of winget installed"
    value: ${{ steps.winget-version.outputs.winget-version }}
runs:
# Hacked together https://github.com/microsoft/winget-cli/issues/1861#issuecomment-1352784247
# https://github.com/microsoft/winget-cli/issues/700#issuecomment-874084714
  using: composite
  steps:
    - name: Download Microsoft.UI.Xaml v2.8.6
      shell: powershell
      run: | # $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri https://www.nuget.org/api/v2/package/Microsoft.UI.Xaml/2.8.6 -OutFile .\microsoft.ui.xaml.2.8.6.zip

    - name: Unzip Microsoft.UI.Xaml v2.8.6
      shell: powershell
      run: |
        Expand-Archive .\microsoft.ui.xaml.2.8.6.zip

    - name: Download Microsoft.VCLibs.x64.14.00.Desktop
      shell: powershell
      run: | # $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Uri https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx -OutFile Microsoft.VCLibs.x64.14.00.Desktop.appx

    - name: Determine Latest winget release via GitHub API
      id: github_api
      shell: powershell
      run: | #  $ProgressPreference = 'SilentlyContinue' #181234098  
        if ("${{ inputs.GITHUB_TOKEN }}" -ne "NONE") {
          $headers = @{ "Authorization" = "Bearer ${{ inputs.GITHUB_TOKEN }}" }
          Write-Host "Token present"
        } else {
          $headers = @{}
          Write-Host "No token present"
        }

        $gitHubReleasesResponse = Invoke-RestMethod https://api.github.com/repos/microsoft/winget-cli/releases/164835566  -Headers $headers   
        $wingetReleaseAssets = $gitHubReleasesResponse.assets
        $latestWingetMsixBundleUri = $wingetReleaseAssets.browser_download_url | Where-Object {$_.EndsWith(".msixbundle")}
        $latestWingetLicenseXmlUri = $wingetReleaseAssets.browser_download_url | Where-Object {$_.EndsWith("License1.xml")}
        Write-Host "latest_winget_msix_bundle_uri=$latestWingetMsixBundleUri"
        Write-Host "latest_winget_license_xml_uri=$latestWingetLicenseXmlUri"
        Write-Output "latest_winget_msix_bundle_uri=$latestWingetMsixBundleUri" >> $Env:GITHUB_OUTPUT
        Write-Output "latest_winget_license_xml_uri=$latestWingetLicenseXmlUri" >> $Env:GITHUB_OUTPUT

    - name: Download winget
      shell: powershell
      run: | # $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Headers $headers -Uri "${{ steps.github_api.outputs.latest_winget_msix_bundle_uri }}" -OutFile "./winget.msixbundle"

    - name: Download License
      shell: powershell
      run: | # $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Headers $headers -Uri "${{ steps.github_api.outputs.latest_winget_license_xml_uri }}" -OutFile "./winget_License1.xml"

    - name: Install Microsoft.UI.Xaml v2.8.6
      shell: powershell
      run: |
        Add-AppxPackage .\microsoft.ui.xaml.2.8.6\tools\AppX\x64\Release\Microsoft.UI.Xaml.2.8.appx

    - name: Install Microsoft.VCLibs.x64.14.00.Desktop
      shell: powershell
      run: |
        Add-AppxPackage Microsoft.VCLibs.x64.14.00.Desktop.appx

    - name: Provisioning Winget
      shell: powershell
      run: |
        echo "PROVISIONING WINGET"
        Add-AppxProvisionedPackage -Online -PackagePath ./winget.msixbundle -LicensePath ./winget_License1.xml

    - name: Installing Winget
      shell: powershell
      run: |
        echo "INSTALLING WINGET"
        Add-AppxPackage .\winget.msixbundle

    - name: Cleanup Downloads
      shell: powershell
      run: |
        rm Microsoft.VCLibs.x64.14.00.Desktop.appx
        rm ./winget_License1.xml
        rm ./winget.msixbundle
        Remove-Item -Recurse -Force .\microsoft.ui.xaml.2.8.6

    # FIX by air-hand. SEE https://github.com/Cyberboss/install-winget/pull/4
    - name: Wait to allow Installation to Finalize
      shell: powershell
      run: |
        foreach ($i in 1..10) {
          Start-Sleep -Seconds 3
          Write-Host "Waiting for winget to install... ${i}"
          if (Get-Command winget -ErrorAction SilentlyContinue) {
            break
          }
        }
        echo "START executing Get-AppxPackage "  
        Get-AppxPackage -AllUsers -Name "*winget*"  
        echo "END OF executing Get-AppxPackage "  

    - name: Output winget Version
      id: winget-version
      shell: powershell
      run: |
        $version=winget --version
        Write-Host "$version"
        Write-Output "winget-version=$version" >> $Env:GITHUB_OUTPUT
