name: 'Test Action 2'

on:
  push:
    branches: [main, blessio-patch-1]

jobs:
  test-job:
    name: Test Job (No GitHub token)
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install winget
      id: install-winget
      uses: blessio/install-winget@blessio-patch-1

    - name: Check Version
      shell: bash
      run: |
        VERSION="${{ steps.install-winget.outputs.winget-version }}"
        if [ -z "$VERSION" ]; then
          exit 1
        fi
        echo $VERSION

    - name: Install wingetcreate
      run: winget install wingetcreate --disable-interactivity --accept-source-agreements --accept-package-agreements

  test-job-with-token:
    name: Test Job with GitHub Token
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-2022', 'windows-latest' ]
        repeat: [ 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z' ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install winget
      id: install-winget
      uses: blessio/install-winget@blessio-patch-1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check Version
      shell: bash
      run: |
        VERSION="${{ steps.install-winget.outputs.winget-version }}"
        if [ -z "$VERSION" ]; then
          exit 1
        fi
        echo $VERSION

    - name: Install wingetcreate
      run: winget install wingetcreate --disable-interactivity --accept-source-agreements
