name: 'Test Action 2'

on:
  push:
    branches: [main, blessio-patch-1]

jobs:
  test-job:
    name: Test Job (No GitHub token)
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install winget
      id: install-winget
      uses: blessio/install-winget@blessio-patch-1
      with: 
        get_release_id: '164835566'

    - name: Check Version
      shell: bash
      run: |
        VERSION="${{ steps.install-winget.outputs.winget-version }}"
        if [ -z "$VERSION" ]; then
          exit 1
        fi
        echo $VERSION

    - name: Install wingetcreate
      run: winget install wingetcreate --disable-interactivity --accept-source-agreements --accept-package-agreements

  test-job-with-token:
    name: Test Job with GitHub Token
    strategy:
      fail-fast: false
      matrix:
        os: [ 'windows-2022', 'windows-latest' ]
        repeat: [ 'a', 'b', 'c', 'd', 'e', 'f', 'g'  ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install winget
      id: install-winget
      uses: blessio/install-winget@blessio-patch-1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        wget_release_id: '164835566'

    - name: Check Version
      shell: bash
      run: |
        VERSION="${{ steps.install-winget.outputs.winget-version }}"
        if [ -z "$VERSION" ]; then
          exit 1
        fi
        echo $VERSION

    - name: Install wingetcreate
      run: winget install wingetcreate --disable-interactivity --accept-source-agreements
